### ISSUE TITLE
Weekly view error

### ISSUE THREAD

**Issue by gmill20** [coroo/chart-js-integration#15]
When adding in the extra weekly option the following error is thrown.

          ->options([
                    'latestData' => 6 // in months
                    'uom' => 'week' // available in 'week', 'month'
                ])
            ->width('full')
            ->canSee(function ($request) {
                return $request->user()->hasrole('Super Admin|Admin');
            }),
        ];
    }
 
Arguments
"syntax error, unexpected ''uom'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'"

**Comment by coroo** [comment]
Sorry, my mistake in tutorial information. 
Can you please add comma (,) after number 6:
```
     'latestData' => 6,
     'uom' => 'week'
```

**Comment by gmill20** [comment]
Brilliant that worked.

**Comment by gmill20** [comment]
Possible for daily stats?! is that doable?

**Comment by coroo** [comment]
> Possible for daily stats?! is that doable?

Will try to do enhancement in this issue list:
https://github.com/coroo/chart-js-integration/issues/16
