### ISSUE TITLE
Week number is out

### ISSUE THREAD

**Issue by gmill20** [coroo/chart-js-integration#17]
Noticed the week numbers start at 0, Week number should start at 1 (I noticed my stats for week 50 was actually week 49) 

E.g W0 2020 should be W1 2020.
https://www.epochconverter.com/weeks/2019

<img width="217" alt="screenshot_3962" src="https://user-images.githubusercontent.com/11597797/71729190-fdd61980-2e36-11ea-91ce-bf68f9c5fb7d.png">

**Comment by gmill20** [comment]
I think it is making the week numbers go from Sunday to Sunday. I think the standard is Monday to Sunday or Sunday to Sat. Would be hand yif we could choose with an option.

**Comment by coroo** [comment]
Hi @gmill20 , sorry for late response. 
Let me check first and add this options in our next feature.

**Comment by gmill20** [comment]
Ok cool.
I cannot work out what it is actually doing. it is kind of right but not if you know what i mean. 

Current week lead outcomes looks like it is starting from monday. 
Total is 4 and correct. W1 2020

 ->options([
                    'latestData' => 1, // in months
                    'uom' => 'week' // available in 'week', 'month'

Weekly Lead Outcomes  W1 2020 is showing 14 total. Correct if the week starts from Sunday. 

 ->options([
                    'latestData' => 12, // in months
                    'uom' => 'week' // available in 'week', 'month'

<img width="1338" alt="screenshot_3965" src="https://user-images.githubusercontent.com/11597797/71813427-7b856980-3071-11ea-9bf6-852b48f78dff.png">

**Comment by coroo** [comment]
Hi @gmill20 , 
For the latest version (0.0.13), i use yearweek instead of week. Also, i do change for some sorting problem in weekly view. For your idea about using option to start week from monday or sunday, please refer to this new documentation: https://github.com/coroo/chart-js-integration#set-up-weekly-view

If you found any issue again, please dont hestiate to create any issue.

Again, thank you for reaching me out about this issue.

**Comment by gmill20** [comment]
Brilliant that looks great now! 
I wondered if it is possible to add in the % at the side of the total numbers. 
Really great package for nova this.

**Comment by coroo** [comment]
Hi @gmill20 , thank you.

Which % that will need to show? 
Do you mean % in legend, e.g. Average Sales #1 (70%), Average Sales #2 (30%) ?

**Comment by gmill20** [comment]
Yes, so if total is 118,

Avg sales 1 = (23  19.49%)
Avg sales 2 = (50  42.37%)
Avg sales 3 = (27   22.88%)
Avg sales 4 = (18   15.25%)

Maybe they could be rounded up.

**Comment by coroo** [comment]
Ok, I will create different ticket for that one :)
